### ISSUE TITLE
Make `kill-*` targets to use the exit code of `neuro kill`

### ISSUE THREAD

**Issue by mariyadavydova** [neuro-inc/cookiecutter-neuro-project#327]
Since v20.01.15, `neuro kill` returns non-zero exit code if the job to be killed is not found. The current version of the template ignores this code.

Let's reuse the idea from the `make kill-train-all` target and kill only the jobs which are currently running.

**Comment by ayushkovskiy** [comment]
I like the idea to kill only running jobs, in this way:

https://github.com/neuromation/cookiecutter-neuro-project/blob/d0e2095c7f3120b06668f3c1c673abe6af34fb35/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L335

However, in order not to kill other project's jobs by accident, we need to do filtering the jobs by project.

The problem is that the jobs' description field does not have a fixed format (for non-hyperparameter jobs it looks like [`"$(PROJECT_ID):train"`](https://github.com/neuromation/cookiecutter-neuro-project/blob/d0e2095c7f3120b06668f3c1c673abe6af34fb35/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile#L310), for hyperparameter jobs it will look like [`"$(PROJECT_ID):train:$(SWEEP_REAL)"`](https://github.com/neuromation/cookiecutter-neuro-project/pull/307/files#diff-21cd6e8e5fd83b2e927adbe64c6966e6R380)). Currently, `neuro ps --description` does not support patterns, it works only with exact string match. The proper way to solve this would be to implement filtering by pattern in `neuro ps --description`, and then modify targets to use these values, for exapmle, `kill-all` would look as `$(NEURO) kill $($(NEURO) ps --description "$(PROJECT_ID):*")`.

**Comment by mariyadavydova** [comment]
I'm not sure if we really need patterns in description search. What we need for this feature is "contains" relation (i.e. kill-all kills all jobs where description contains the project I'd).

On the Web dashboard we have a filtering functionality which checks if any job text property (id, name, description, command) contains a given text fragment. Can we probably implement such a feature in CLI? What do you think, @asvetlov ?

**Comment by asvetlov** [comment]
CLI can filter on name, status, and description now, custom categories are not supported.
Filtering by id and command are almost useless.
After discussing on daily meeting we had an agreement that *labels* can solve the need.
See https://github.com/neuromation/platform-client-python/issues/1273 for the context.

**Comment by YevheniiSemendiak** [comment]
outdated
