### ISSUE TITLE
Strange error when training process stops

### ISSUE THREAD

**Issue by mariyadavydova** [neuro-inc/cookiecutter-neuro-project#329]
See my output:

```
Streaming logs of the job train-tqdm-demo-jan21-base
neuro exec --no-key-check -T train-tqdm-demo-jan21-base "tail -f /output" || echo -e "Stopped streaming logs.\nUse 'neuro logs <job>' to see full logs."
Warning: Permanently added 'ssh-auth.neuro-ai-public.org.neu.ro,34.70.170.242' (ECDSA) to the list of known hosts.
Starting SSH server
Long process starts...
 98%|█████████▊| 980/1000 [00:09<00:00, 98.49it/s]command terminated with exit code 137
-e Stopped streaming logs.
Use 'neuro logs <job>' to see full logs.
```

**Comment by ayushkovskiy** [comment]
This error is expected since once the job dies, the command `neuro exec --no-key-check -T train-tqdm-demo-jan21-base "tail -f /output"` fails. What we can do is to mute its stderr via `2>/dev/null`, which I consider dangerous (bad idea to mute all error output). In order for the whole target not to fail, we have `|| echo -e "Stopped streaming logs.\nUse ...` at the end, which tells you "that's OK, check your `neuro logs`" and returns `0` exit code.

Not an issue from my perspective.

**Comment by ayushkovskiy** [comment]
Note, that `command terminated with exit code 137` is a valid output of the `tail -f` command that was interrupted when the container has died.

**Comment by YevheniiSemendiak** [comment]
outdated
