### ISSUE TITLE
Change Template paradigm to dump it fully on Storage

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#356]
See https://neuromation.slack.com/archives/CU7EY0YRE/p1582237587022800

Proposal:
1. move data folder to `/data` in the job
2. mount whole project's directory to the storage (so that Makefile and everything else is being dumped to storage)
3. instead of `neuro cp --update` separately code, config, etc., we'll `neuro cp --update` the whole project's directory at once.

**Comment by ayushkovskiy** [comment]
@mariyadavydova :
"""
Thank you! However, your 3rd point contradict your 1st one. Let's keep the /data folder inside the project structure for the cases when data is small (say, several MB of text). When data is large, people tend to use buckets, and we'll add the bucket support to the template as we get them.
"""

**Comment by ayushkovskiy** [comment]
Having a separate `/data` outside the project will allow us to copy to Storage and mount to the job the whole project's folder, which will simplify Template drastically. We don't want to encourage the users to use `neuro cp` for datasets, it's inefficient.
So I don't think it's a contradiction.

**Comment by mariyadavydova** [comment]
The question about the project structure and location of various types of data is actually more interesting than the question about data location. Let me think out loud.

When it comes to the parts of the project, there are three major components:

* Project files (python scripts, notebooks, configs, etc):
  - should be under Git; 
  - should always be in sync between local machine and storage.
* Data:
  - should not be under Git;
  - should be on storage or in buckets;
  - doesn't have to be on a local machine
* Artifacts (we call them results now - logs and models):
  - the same as data; the difference is that user copies data from somewhere to the platform, while artifacts are copied from the platform to somewhere.

Then, I see two options for now:

* Create three folders on storage (`/<project-slug>`, `/<project-slug>-data`, and `/<project-slug>-artifacts`) and mount them to 3 directories in Docker container (`/project`, `/data`, `/artifacts`). 
* Keep everything inside the project structure (just sync it as a whole entity) for now and make things better when we have buckets available.

What do you think?

**Comment by ayushkovskiy** [comment]
0. I fully support the idea of mounting project to the constant path `/project`:
https://github.com/neuromation/cookiecutter-neuro-project/pull/354
1. no need to separate artifacts, we can work with them in the same way as with code/config/etc. Only data needs to be separated as it can be mounted from other places, not just from Storage.
Note, we already have --exclude command: `neuro cp ... --exclude ...` (see https://github.com/neuromation/platform-client-python/pull/1276 and https://github.com/neuromation/platform-client-python/pull/1295).

Yes, the problem here is: where on Storage to put `data/` folder? I see the `<project-slug>-data/` a dirty solution as it does not match your local file structure. 
We could sync code/config/results with Storage using `--exclude="./data/"`, and have a separate target `make upload-data` which, as it is now, uploads data to the Storage to `storage:<project-slug>/data`, but only when run explicitly.

2. What will be different when we have buckets available? We'll still be having:
- locally: `./<project-slug>/`, `./<project-slug>/data`
- Storage: `storage:<project-slug>/`, `storage:<project-slug>/data`
- Job: `/project`, `/data`

**Comment by ayushkovskiy** [comment]
NOTE: need to think also not to upload files from `.gitignore` -- neuro can't do it now unfortunately.

**Comment by yartem** [comment]
artifacts can be now excluded from sync (`--exclude` , `--include`)

**Comment by yartem** [comment]
Implemented as POC in [Project 0](https://github.com/neuromation/ml-recipe-project-zero/)

**Comment by YevheniiSemendiak** [comment]
outdated, now we define each folder in project as a separate volume on a storage and upload / mount them also separately
