### ISSUE TITLE
Support applying Template to existing GitHub project

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#70]

**Comment by mariyadavydova** [comment]
Recipe:

1. Go to a parent directory of your project (e.g. in `ai-kits`).
2. Run `cookiecutter gh:neuromation/cookiecutter-neuro-project -f` and re-enter the appropriate parameters (be especially accurate with `project_slug` and `code_directory`). Due to `-f` option this command overwrites the template-related content in your project directory (e.g. in `nlp`).
3. Use a tool you prefer to resolve git conflicts (mostly in `README` and `Makefile`).
4. Commit, push, profit!

**Comment by anayden** [comment]
Is this resolved by the recipe above? :)

**Comment by ayushkovskiy** [comment]
I suppose so

**Comment by mariyadavydova** [comment]
I will add this to README (both of them).

**Comment by ayushkovskiy** [comment]
Yesterday I checked, indeed, `cookicutter gh:... -f` works on already created projects.

**Comment by ayushkovskiy** [comment]
@mariyadavydova , we need to ensure that this information is present in our documentation. This issue is resolved

**Comment by YevheniiSemendiak** [comment]
this issue was discussed a lot and we didn't reach a consensus.
1. Overwriting files leads to errors
2. Resolving git conflicts is annoying the same as asking to replace each file

As for me, the only way, for now, to apply the template to the existing project is to manually integrate each part of it.
